// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnF0OWI_WUNOVxa_Odc5Q2fFsGMa0lEuM',
    appId: '1:937110532047:web:751292d7916b5e1e41acba',
    messagingSenderId: '937110532047',
    projectId: 'mental-health-6b776',
    authDomain: 'mental-health-6b776.firebaseapp.com',
    storageBucket: 'mental-health-6b776.appspot.com',
    measurementId: 'G-Y1C7WL7KDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKl7iSHrVtTJTT_FkrsfkSOUg9jqHeOBM',
    appId: '1:937110532047:android:41da9c4053e67e7f41acba',
    messagingSenderId: '937110532047',
    projectId: 'mental-health-6b776',
    storageBucket: 'mental-health-6b776.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMrH7eEqs4plvGoqenDmN6-lxHEKxzymY',
    appId: '1:937110532047:ios:758b508465a1d95d41acba',
    messagingSenderId: '937110532047',
    projectId: 'mental-health-6b776',
    storageBucket: 'mental-health-6b776.appspot.com',
    iosBundleId: 'com.example.mentalHealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMrH7eEqs4plvGoqenDmN6-lxHEKxzymY',
    appId: '1:937110532047:ios:758b508465a1d95d41acba',
    messagingSenderId: '937110532047',
    projectId: 'mental-health-6b776',
    storageBucket: 'mental-health-6b776.appspot.com',
    iosBundleId: 'com.example.mentalHealth',
  );
}
